# 과제 1

## Matrix 구현 
1. Linear Regression에서 쓰이는 **정규방정식**을 행렬로 구현하고, sklearn 혹은 OLS 패키지를 통해 구한 **실제 값과 비교**해주세요.
2. LSE에서 쓰이는 Loss Function, **MSE**를 행렬로 구현해 출력해주세요.

### Data Load 

In [3]:
import pandas as pd
data = pd.read_csv("assignment1.csv")

In [4]:
data.head()

y    x1    x2  x3   x4    x5
0  10  38.9  64.7   4  868  59.7
1  13  41.6  45.3  -4  957  61.4
2  11  39.7  74.1   8  786  61.0
3   7  37.3  48.0  19  984  67.5
4  10  39.5  51.9   6  700  57.2

In [5]:
data.shape     # y:(9,1), X:(9,5)

(9, 6)

In [6]:
X = data.drop(["y"], axis=1)
y = data.y

In [7]:
# Matrix 계산을 위해 X와 y를 numpy 형태로 바꾸어줍니다. 
X = X.to_numpy()
y = y.to_numpy()

In [8]:
X

array([[  38.9,   64.7,    4. ,  868. ,   59.7],
       [  41.6,   45.3,   -4. ,  957. ,   61.4],
       [  39.7,   74.1,    8. ,  786. ,   61. ],
       [  37.3,   48. ,   19. ,  984. ,   67.5],
       [  39.5,   51.9,    6. ,  700. ,   57.2],
       [  37.4,   53.6,   -5. , 1037. ,   58.8],
       [  35.1,   71.4,    3. ,  986. ,   58.6],
       [  38.8,   58.3,    6. ,  819. ,   59.2],
       [  36.6,   52.6,  -19. ,  791. ,   54.4]])

In [9]:
y

array([10, 13, 11,  7, 10,  9,  9,  6,  5], dtype=int64)

### 1. Normal Equation 정규방정식

**선형방정식**   
$y_1 = \beta_0 + \beta_1x_{11} + \beta_2x_{12} + \beta_3x_{13} + \beta_4x_{14} + \beta_5x_{15} + \varepsilon_1$   
$y_2 = \beta_0 + \beta_1x_{21} + \beta_2x_{22} + \beta_3x_{23} + \beta_4x_{24} + \beta_5x_{25} + \varepsilon_2$   
...   
$y_n = \beta_0 + \beta_1x_{n1} + \beta_2x_{n2} + \beta_3x_{n3} + \beta_4x_{n4} + \beta_5x_{n5} + \varepsilon_n$
<br>
<br>
<br>
**행렬 표현**    
$
\begin{equation*}
\begin{pmatrix} 
   y_{1}\\
   y_{2}\\
   \cdots \\
   y_{n}\\
\end{pmatrix}=
\begin{pmatrix}
1 & x_{11} & x_{12} &  x_{13} & x_{14} & x_{15} \\
1 & x_{21} & x_{22} &  x_{13} & x_{14} & x_{25} \\
\vdots  & \vdots  & \ddots & \vdots  \\
1 & x_{n1} & x_{n2} &  x_{13} & x_{14} & x_{n5} 
\end{pmatrix}
\begin{pmatrix} 
   \beta_{0}\\
   \beta_{1}\\
   \cdots \\
   \beta_{5}\\
\end{pmatrix}+
\begin{pmatrix} 
   \varepsilon_{1}\\
   \varepsilon_{2}\\
   \cdots \\
   \varepsilon_{n}\\
\end{pmatrix}
\end{equation*}
$    
$y = X\beta + \varepsilon$ 으로 $\beta$ 가중치와 $X$ 값의 행렬을 곱해서 $y$ 값을 예측하고 있다.
<br>
<br>
<br>
**오차(실제값 - 예측값) 제곱의 합**    

$\varepsilon$ : nx1행렬 → 오차 제곱을 위해 전치를 해야 한다.    
$\sum\limits_{i=1}^{n}\varepsilon_i^2 = \varepsilon'\varepsilon = (y - X\beta)'(y - X\beta) = (y' - \beta'X')(y - X\beta) = y'y + \beta'X'X\beta - 2\beta'X'y$


경사하강법(gradient descent)에 의해 $\partial L$이 0이 될때 최소값을 가지게 된다.   
$\frac{\partial L}{\partial\beta} = 2X'X\beta - 2X'y = 0  →  \beta = (X'X)^{-1}X'y$

In [10]:
import numpy as np
from numpy.linalg import inv 

In [11]:
def estimate_beta(X, y):
    designX = np.concatenate([np.ones((len(y), 1)), X], axis=1)
    beta_hat = np.dot(np.dot(inv(np.dot(designX.T, designX)), designX.T), y)
    return beta_hat

In [ ]:
# designX 코드 풀어보기 ; 𝑋행렬 1열에 1을 추가하는 작업

In [20]:
(len(y), 1)

(9, 1)

In [21]:
np.ones((len(y), 1))  ## 9x1 의 원소가 1인 2차원 배열

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [22]:
[np.ones((len(y), 1)), X]  ## 배열 2개 리스트로 묶기 [(9,1), (9,5)]

[array([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]]),
 array([[  38.9,   64.7,    4. ,  868. ,   59.7],
        [  41.6,   45.3,   -4. ,  957. ,   61.4],
        [  39.7,   74.1,    8. ,  786. ,   61. ],
        [  37.3,   48. ,   19. ,  984. ,   67.5],
        [  39.5,   51.9,    6. ,  700. ,   57.2],
        [  37.4,   53.6,   -5. , 1037. ,   58.8],
        [  35.1,   71.4,    3. ,  986. ,   58.6],
        [  38.8,   58.3,    6. ,  819. ,   59.2],
        [  36.6,   52.6,  -19. ,  791. ,   54.4]])]

In [24]:
designX = np.concatenate([np.ones((len(y), 1)), X], axis=1)    ## axis=1 ; 2차원 배열 좌→우로 합치기
designX

array([[ 1.000e+00,  3.890e+01,  6.470e+01,  4.000e+00,  8.680e+02,
         5.970e+01],
       [ 1.000e+00,  4.160e+01,  4.530e+01, -4.000e+00,  9.570e+02,
         6.140e+01],
       [ 1.000e+00,  3.970e+01,  7.410e+01,  8.000e+00,  7.860e+02,
         6.100e+01],
       [ 1.000e+00,  3.730e+01,  4.800e+01,  1.900e+01,  9.840e+02,
         6.750e+01],
       [ 1.000e+00,  3.950e+01,  5.190e+01,  6.000e+00,  7.000e+02,
         5.720e+01],
       [ 1.000e+00,  3.740e+01,  5.360e+01, -5.000e+00,  1.037e+03,
         5.880e+01],
       [ 1.000e+00,  3.510e+01,  7.140e+01,  3.000e+00,  9.860e+02,
         5.860e+01],
       [ 1.000e+00,  3.880e+01,  5.830e+01,  6.000e+00,  8.190e+02,
         5.920e+01],
       [ 1.000e+00,  3.660e+01,  5.260e+01, -1.900e+01,  7.910e+02,
         5.440e+01]])

In [ ]:
# beta_hat 코드 풀어보기

In [26]:
np.dot(designX.T, designX)    # 𝑋'𝑋 행렬곱

array([[9.000000e+00, 3.449000e+02, 5.199000e+02, 1.800000e+01,
        7.928000e+03, 5.378000e+02],
       [3.449000e+02, 1.324717e+04, 1.988151e+04, 7.082000e+02,
        3.032540e+05, 2.061940e+04],
       [5.199000e+02, 1.988151e+04, 3.086317e+04, 1.190400e+03,
        4.566542e+05, 3.102131e+04],
       [1.800000e+01, 7.082000e+02, 1.190400e+03, 9.240000e+02,
        1.648600e+04, 1.310300e+03],
       [7.928000e+03, 3.032540e+05, 4.566542e+05, 1.648600e+04,
        7.089332e+06, 4.752558e+05],
       [5.378000e+02, 2.061940e+04, 3.102131e+04, 1.310300e+03,
        4.752558e+05, 3.223854e+04]])

In [27]:
inv(np.dot(designX.T, designX))    # (𝑋'𝑋)−1  구한 행렬곱의 역행렬

array([[ 2.13111451e+02, -1.21756821e+00, -3.94872253e-01,
         7.73629493e-01,  1.31798148e-02, -2.62213574e+00],
       [-1.21756821e+00,  5.21038395e-02,  1.50771775e-03,
         4.47690658e-03,  6.09118142e-04, -2.36259498e-02],
       [-3.94872253e-01,  1.50771775e-03,  1.74725096e-03,
        -1.46071042e-03, -2.37466429e-05,  4.35105768e-03],
       [ 7.73629493e-01,  4.47690658e-03, -1.46071042e-03,
         5.86729294e-03,  2.28092916e-04, -1.79644089e-02],
       [ 1.31798148e-02,  6.09118142e-04, -2.37466429e-05,
         2.28092916e-04,  2.48514341e-05, -9.62226000e-04],
       [-2.62213574e+00, -2.36259498e-02,  4.35105768e-03,
        -1.79644089e-02, -9.62226000e-04,  6.96124654e-02]])

In [28]:
np.dot(inv(np.dot(designX.T, designX)), designX.T)  # (𝑋'𝑋)−1𝑋'

array([[-1.80709367e+00, -6.90766931e+00, -7.88795071e+00,
        -5.83975738e-01,  8.40511969e+00,  2.02698606e+00,
         3.83995938e+00,  3.05436150e+00,  8.60262782e-01],
       [ 4.29734602e-02,  1.32636250e-01,  3.60752826e-02,
        -1.12042675e-01,  2.06238165e-02,  3.19941955e-02,
        -5.15318422e-02,  1.90336818e-02, -1.19762170e-01],
       [ 1.01283207e-02, -2.72847982e-03,  2.95194120e-02,
        -1.21901357e-02, -2.11414900e-02, -6.31048235e-03,
         9.97801785e-03, -5.13822140e-03, -2.11694126e-03],
       [ 2.25180922e-03, -1.45003299e-02, -2.64855223e-02,
        -6.17159401e-03,  4.19610447e-02,  1.36603693e-02,
         1.62613252e-02,  2.06929027e-02, -4.76700050e-02],
       [ 3.76626994e-04,  1.23318096e-03, -1.73563667e-03,
        -1.40259580e-03, -2.67235194e-04,  2.73959704e-03,
         1.66570046e-03,  1.87272254e-04, -2.79691005e-03],
       [-1.08773684e-02,  1.73403962e-02,  1.08662916e-01,
         1.16154369e-01, -1.29052490e-01, -8.732291

In [29]:
np.dot(np.dot(inv(np.dot(designX.T, designX)), designX.T), y)   # 𝛽 = (𝑋'𝑋)−1𝑋'𝑦

array([-3.92447368e+01,  1.31232583e+00,  8.53744361e-02,  7.41849897e-02,
        1.50018573e-02, -3.42273652e-01])

In [ ]:
# 함수 적용

In [30]:
beta_hat = estimate_beta(X, y)
beta_hat

array([-3.92447368e+01,  1.31232583e+00,  8.53744361e-02,  7.41849897e-02,
        1.50018573e-02, -3.42273652e-01])

#### 실제 값과 비교

In [31]:
from sklearn.linear_model import LinearRegression

In [32]:
# 선형회귀 모델 생성
model = LinearRegression()
# 모델 적합
model.fit(X, y)

# 동일한 데이터에 대해 예측값 구하기
pred = model.predict(X)

In [33]:
print(model.intercept_)   # intercept
print(model.coef_)   # 추정된 회귀계수 (intercept 제외)

-39.24473678135652
[ 1.31232583  0.08537444  0.07418499  0.01500186 -0.34227365]


### 2. MSE

In [55]:
def MSE(X, y, beta_hat):
    # X행렬 1열에 1원소 추가
    designX = np.concatenate([np.ones((len(y), 1)), X], axis=1)
    # 예측값 구하기
    y_pred = np.dot(designX, beta_hat)
    
    # SSE / n-p-1
    mse = np.sum((y - y_pred)**2) / (len(y) - (X.shape[1] + 1))
    
    return mse

In [56]:
MSE(X, y, estimate_beta(X, y))

4.846793168705768